apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: registry.bluemix.net/k8s-skaffold/skaffold-example
test:
  - image: registry.bluemix.net/k8s-skaffold/skaffold-example
    structureTests:
      - ./test/*
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: icr
    build:
      icr:
        apiKey: "SOMEAPIKEY"
        defaultRegion: "us-south"
  - name: test
    test:
      - image: registry.bluemix.net/k8s-skaffold/skaffold-example
        structureTests:
          - ./test/profile_structure_test.yaml
